name: CI

on:
  push:
    branches:
      - master  # O el nombre de tu rama principal
  pull_request:
    branches:
      - master  # O el nombre de tu rama principal

jobs:
  build:
    runs-on: windows-latest  # Puedes ajustar el sistema operativo según tus necesidades

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'  # Ajusta la versión de .NET Core según tus requisitos

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Run unit tests
      run: dotnet test --configuration Release --logger "trx;LogFileName=testresults.trx"  # Este comando ejecutará las pruebas unitarias y generará un archivo de resultados

    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: TestResults
        path: '**/TestResults/*.trx'  # Ajusta la ruta si los resultados están en otro directorio
