name: CI para CalculadoraString

on:
  push:
    branches:
      - CalculadoraString
  pull_request:
    branches:
      - CalculadoraString

jobs:
  build:
    runs-on: windows-latest  # Utilizamos Windows como sistema operativo

    steps:
    - uses: actions/checkout@v2  # Paso para clonar el repositorio

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1  # Configuramos el entorno .NET
      with:
        dotnet-version: '6.0.x'  # Puedes especificar la versión de .NET que necesitas

    - name: Restore dependencies
      run: dotnet restore  # Restaurar las dependencias del proyecto

    - name: Build and test
      run: dotnet test --no-restore --verbosity normal  # Ejecutar las pruebas unitarias
